### ISSUE TITLE
[BUG] Blacklisting apps doesn't prevent them from showing up in DirectChat

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [Gurjot95/DirectChat-Feedback#10]
**Describe the bug**
Blacklisting apps doesn't prevent them from showing up in Direct Chat. 

**To Reproduce**
1. Go to the settings and open the blacklist
2. Add an app to the list
3. See that the chat bubbles still pop up 

**Expected behavior**
I expect that the blacklisted app will be ignored by DirectChat

**Screenshots**
![Screenshot_20200807-112401_DirectChat](https://user-images.githubusercontent.com/23037821/89677114-ae127180-d8a1-11ea-8ff1-f850202f689d.jpg)
![Screenshot_20200807-111539_DirectChat](https://user-images.githubusercontent.com/23037821/89677118-aeab0800-d8a1-11ea-87b9-452c11127f86.jpg)

**Device**
 - Device Name: Galaxy Note 10 
 - OS: Android 10
 - App Version: 1.8.3

**Comment by Gurjot95** [comment]
Hello, I don't think you get what blacklisting is here for. It won't display chatheads over the top of blacklisted apps. For example, in this case, if Facebook messenger is currently launched, DirectChat won't display any chatheads over the top of this app. This feature is mostly used when you're playing games and you don't want chat head to pop up and interfere with your experience. If you just want to disable it for individual messenger, please head over to apps section and disable appropriate toggle.

**Comment by ThinkDigitalSoftware** [comment]
Oh, I guess I didn't understand. OK, thanks
