### ISSUE TITLE
[Messenger Support Request]

### ISSUE THREAD

**Issue by hamzabutt8595** [Gurjot95/DirectChat-Feedback#18]
**Is your feature request related to a problem? Please describe.**
I cam'ylt reply some messages. I request for messenger developer to support reply notification

**Comment by hamzabutt8595** [comment]
![Screenshot_2020-09-04-21-33-11-89](https://user-images.githubusercontent.com/70768815/92263615-54c84d00-eef6-11ea-96ba-7a00cac9a5f7.jpg)

**Comment by Gurjot95** [comment]
Hey, is that Android Messages app you're using? Please continute discussion in other issue #17
