### ISSUE TITLE
Still seeing ADS

### ISSUE THREAD

**Issue by shae23** [Gurjot95/DirectChat-Feedback#6]
Bought the app when it was still premium, recieved a code to redeem for premium access, did that, still seeing ADS, like bro this ain't the experience I signed up for when I bought this

**Comment by Gurjot95** [comment]
I am sorry for the issue. You shouldn't see ads if you're premium user. Can
you still access premium features? Does premium screen shows you have
unlocked all features?

Regards
Gurjot Singh

**Comment by shae23** [comment]
This is what happens, if I restart my phone or I disconnect from the internet for a while then reconnect, ads start popping up in the chat window, when I open the app itself, ads display for a second then disappear and I seem to be premium

**Comment by Gurjot95** [comment]
Yes, as of now, it needs internet connectivity at every launch to verify
the premium membership. I will probably change the implementation so it
doesn't need to check every time.

Regards
Gurjot Singh

**Comment by shae23** [comment]
Ok I guess, that's a little sucky though, I dislike it, which is why I opted for the pro version



Get BlueMail for Android

**Comment by Gurjot95** [comment]
Yeah I get your point. I have some ideas on how I can improve this process
in next update.

Regards
Gurjot Singh

**Comment by Gurjot95** [comment]
Fixed in latest update
