### ISSUE TITLE
Ads appear on chats although I purchased a premium license

### ISSUE THREAD

**Issue by wwwyaron** [Gurjot95/DirectChat-Feedback#7]
Only when I open Directchat app itself, it disappears after a few seconds.

**Comment by Gurjot95** [comment]
I will be fixing that in next update. Also duplicate of #6

Regards
Gurjot Singh

**Comment by wwwyaron** [comment]
Thank you. When can we expect that?

**Comment by Gurjot95** [comment]
Should be fixed now in latest update. Closing the issue now.
